In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("src/data/housing/2007-2016-homeless-texas.csv")

In [3]:
df.head()

,Year,State,CoC Number,CoC Name,Measures,Count
0,1/1/2007,TX,TX-500,San Antonio/Bexar County CoC,Chronically Homeless Individuals,218
1,1/1/2007,TX,TX-500,San Antonio/Bexar County CoC,Homeless Individuals,"1,375"
2,1/1/2007,TX,TX-500,San Antonio/Bexar County CoC,Homeless People in Families,872
3,1/1/2007,TX,TX-500,San Antonio/Bexar County CoC,Sheltered Chronically Homeless Individuals,96
4,1/1/2007,TX,TX-500,San Antonio/Bexar County CoC,Sheltered Homeless,"1,798"

In [4]:
df.nunique()

Year            9
State           1
CoC Number     11
CoC Name       11
Measures       42
Count         844
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2244 entries, 0 to 2243
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Year        2244 non-null   object
 1   State       2244 non-null   object
 2   CoC Number  2244 non-null   object
 3   CoC Name    2244 non-null   object
 4   Measures    2244 non-null   object
 5   Count       2244 non-null   object
dtypes: object(6)
memory usage: 105.3+ KB

In [6]:
df['Year'] = pd. to_datetime(df['Year'])

In [7]:
df['Year']= pd.DatetimeIndex(df['Year']).year

In [8]:
df.head()

,Year,State,CoC Number,CoC Name,Measures,Count
0,2007,TX,TX-500,San Antonio/Bexar County CoC,Chronically Homeless Individuals,218
1,2007,TX,TX-500,San Antonio/Bexar County CoC,Homeless Individuals,"1,375"
2,2007,TX,TX-500,San Antonio/Bexar County CoC,Homeless People in Families,872
3,2007,TX,TX-500,San Antonio/Bexar County CoC,Sheltered Chronically Homeless Individuals,96
4,2007,TX,TX-500,San Antonio/Bexar County CoC,Sheltered Homeless,"1,798"

In [9]:
df = df.drop(columns =['State','CoC Name'])

In [10]:
df['Count'] = df['Count'].str.replace(',', '')

In [11]:
df['Count'] = df['Count'].astype('int64')

In [12]:
df.isnull().sum()

Year          0
CoC Number    0
Measures      0
Count         0
dtype: int64

In [13]:
df['Measures'].value_counts()

Chronically Homeless Individuals                               99
Homeless People in Families                                    99
Sheltered Chronically Homeless Individuals                     99
Sheltered Homeless                                             99
Sheltered Homeless Individuals                                 99
Sheltered Homeless People in Families                          99
Total Homeless                                                 99
Unsheltered Chronically Homeless Individuals                   99
Unsheltered Homeless                                           99
Unsheltered Homeless Individuals                               99
Unsheltered Homeless People in Families                        99
Homeless Individuals                                           99
Sheltered Homeless Veterans                                    66
Unsheltered Homeless Veterans                                  66
Unsheltered Chronically Homeless People in Families            66
Unsheltered Chronically Homeless                               66
Sheltered Chronically Homeless                                 66
Sheltered Chronically Homeless People in Families              66
Homeless Veterans                                              66
Chronically Homeless People in Families                        66
Chronically Homeless                                           66
Sheltered Homeless Unaccompanied Youth (Under 25)              22
Unsheltered Parenting Youth Age 18-24                          22
Unsheltered Parenting Youth (Under 25)                         22
Unsheltered Homeless Unaccompanied Youth (Under 25)            22
Unsheltered Homeless Unaccompanied Young Adults (Age 18-24)    22
Unsheltered Homeless Unaccompanied Children (Under 18)         22
Unsheltered Children of Parenting Youth                        22
Sheltered Parenting Youth Under 18                             22
Sheltered Parenting Youth Age 18-24                            22
Sheltered Parenting Youth (Under 25)                           22
Children of Parenting Youth                                    22
Sheltered Homeless Unaccompanied Young Adults (Age 18-24)      22
Sheltered Homeless Unaccompanied Children (Under 18)           22
Sheltered Children of Parenting Youth                          22
Parenting Youth Under 18                                       22
Parenting Youth Age 18-24                                      22
Parenting Youth (Under 25)                                     22
Homeless Unaccompanied Youth (Under 25)                        22
Homeless Unaccompanied Young Adults (Age 18-24)                22
Homeless Unaccompanied Children (Under 18)                     22
Unsheltered Parenting Youth Under 18                           22
Name: Measures, dtype: int64

In [14]:
df.shape

(2244, 4)

In [15]:
df['Index'] = df['Measures']

In [16]:
df_1 = df.pivot_table('Count', ['Year','CoC Number'], 'Index')

In [17]:
df_1

Index            Children of Parenting Youth  Chronically Homeless  \
Year CoC Number
2007 TX-500                              NaN                   NaN
     TX-503                              NaN                   NaN
     TX-600                              NaN                   NaN
     TX-601                              NaN                   NaN
     TX-603                              NaN                   NaN
...                                      ...                   ...
2016 TX-607                            156.0                 853.0
     TX-611                             35.0                  85.0
     TX-624                              0.0                  36.0
     TX-700                             56.0                 516.0
     TX-701                              1.0                  10.0

Index            Chronically Homeless Individuals  \
Year CoC Number
2007 TX-500                                 218.0
     TX-503                                 443.0
     TX-600                                 574.0
     TX-601                                 479.0
     TX-603                                 208.0
...                                           ...
2016 TX-607                                 823.0
     TX-611                                  75.0
     TX-624                                  36.0
     TX-700                                 511.0
     TX-701                                  10.0

Index            Chronically Homeless People in Families  \
Year CoC Number
2007 TX-500                                          NaN
     TX-503                                          NaN
     TX-600                                          NaN
     TX-601                                          NaN
     TX-603                                          NaN
...                                                  ...
2016 TX-607                                         30.0
     TX-611                                         10.0
     TX-624                                          0.0
     TX-700                                          5.0
     TX-701                                          0.0

Index            Homeless Individuals  Homeless People in Families  \
Year CoC Number
2007 TX-500                    1375.0                        872.0
     TX-503                    3116.0                       2165.0
     TX-600                    2046.0                       1362.0
     TX-601                    1550.0                       1326.0
     TX-603                     804.0                        437.0
...                               ...                          ...
2016 TX-607                    3898.0                       2150.0
     TX-611                     445.0                        147.0
     TX-624                     204.0                         52.0
     TX-700                    3055.0                        976.0
     TX-701                      80.0                         81.0

Index            Homeless Unaccompanied Children (Under 18)  \
Year CoC Number
2007 TX-500                                             NaN
     TX-503                                             NaN
     TX-600                                             NaN
     TX-601                                             NaN
     TX-603                                             NaN
...                                                     ...
2016 TX-607                                            69.0
     TX-611                                             0.0
     TX-624                                            12.0
     TX-700                                            17.0
     TX-701                                             0.0

Index            Homeless Unaccompanied Young Adults (Age 18-24)  \
Year CoC Number
2007 TX-500                                                  NaN
     TX-503                                                  NaN
     TX-600                                                  NaN
     TX-601                                                  NaN
     TX-603                                                  NaN
...                                                          ...
2016 TX-607                                                388.0
     TX-611                                                  1.0
     TX-624                                                 18.0
     TX-700                                                222.0
     TX-701                                                  6.0

Index            Homeless Unaccompanied Youth (Under 25)  Homeless Veterans  \
Year CoC Number
2007 TX-500                                          NaN                NaN
     TX-503                                          NaN                NaN
     TX-600                                          NaN                NaN
     TX-601                                          NaN                NaN
     TX-603                                          NaN                NaN
...                                                  ...                ...
2016 TX-607                                        457.0               64.0
     TX-611                                          1.0               57.0
     TX-624                                         30.0                0.0
     TX-700                                        239.0              523.0
     TX-701                                          6.0                4.0

Index            ...  Unsheltered Homeless  Unsheltered Homeless Individuals  \
Year CoC Number  ...
2007 TX-500      ...                 449.0                             430.0
     TX-503      ...                3886.0                            2343.0
     TX-600      ...                 367.0                             363.0
     TX-601      ...                 201.0                             201.0
     TX-603      ...                 273.0                             273.0
...              ...                   ...                               ...
2016 TX-607      ...                2388.0                            2215.0
     TX-611      ...                  20.0                              20.0
     TX-624      ...                  22.0                              22.0
     TX-700      ...                1196.0                            1186.0
     TX-701      ...                  11.0                               6.0

Index            Unsheltered Homeless People in Families  \
Year CoC Number
2007 TX-500                                         19.0
     TX-503                                       1543.0
     TX-600                                          4.0
     TX-601                                          0.0
     TX-603                                          0.0
...                                                  ...
2016 TX-607                                        173.0
     TX-611                                          0.0
     TX-624                                          0.0
     TX-700                                         10.0
     TX-701                                          5.0

Index            Unsheltered Homeless Unaccompanied Children (Under 18)  \
Year CoC Number
2007 TX-500                                                    NaN
     TX-503                                                    NaN
     TX-600                                                    NaN
     TX-601                                                    NaN
     TX-603                                                    NaN
...                                                            ...
2016 TX-607                                                   47.0
     TX-611                                                    0.0
     TX-624                                                    0.0
     TX-700                                                    4.0
     TX-701                                                    0.0

Index            Unsheltered Homeless Unaccompanied Young Adults (Age 18-24)  \
Year CoC Number
2007 TX-500                                                    NaN
     TX-503                                                    NaN
     TX-600                                                    NaN
     TX-601                                                    NaN
     TX-603                                                    NaN
...                                                            ...
2016 TX-607                                                  218.0
     TX-611                                                    1.0
     TX-624                                                    0.0
     TX-700                                                   73.0
     TX-701                                                    0.0

Index            Unsheltered Homeless Unaccompanied Youth (Under 25)  \
Year CoC Number
2007 TX-500                                                    NaN
     TX-503                                                    NaN
     TX-600                                                    NaN
     TX-601                                                    NaN
     TX-603                                                    NaN
...                                                            ...
2016 TX-607                                                  265.0
     TX-611                                                    1.0
     TX-624                                                    0.0
     TX-700                                                   77.0
     TX-701                                                    0.0

Index            Unsheltered Homeless Veterans  \
Year CoC Number
2007 TX-500                                NaN
     TX-503                                NaN
     TX-600                                NaN
     TX-601                                NaN
     TX-603                                NaN
...                                        ...
2016 TX-607                               24.0
     TX-611                                3.0
     TX-624                                0.0
     TX-700                              147.0
     TX-701                                0.0

Index            Unsheltered Parenting Youth (Under 25)  \
Year CoC Number
2007 TX-500                                         NaN
     TX-503                                         NaN
     TX-600                                         NaN
     TX-601                                         NaN
     TX-603                                         NaN
...                                                 ...
2016 TX-607                                         6.0
     TX-611                                         0.0
     TX-624                                         0.0
     TX-700                                         0.0
     TX-701                                         0.0

Index            Unsheltered Parenting Youth Age 18-24  \
Year CoC Number
2007 TX-500                                        NaN
     TX-503                                        NaN
     TX-600                                        NaN
     TX-601                                        NaN
     TX-603                                        NaN
...                                                ...
2016 TX-607                                        6.0
     TX-611                                        0.0
     TX-624                                        0.0
     TX-700                                        0.0
     TX-701                                        0.0

Index            Unsheltered Parenting Youth Under 18
Year CoC Number
2007 TX-500                                       NaN
     TX-503                                       NaN
     TX-600                                       NaN
     TX-601                                       NaN
     TX-603                                       NaN
...                                               ...
2016 TX-607                                       0.0
     TX-611                                       0.0
     TX-624                                       0.0
     TX-700                                       0.0
     TX-701                                       0.0

[99 rows x 42 columns]

In [18]:
df_1.reset_index(drop = False, inplace = True)

In [19]:
df_1.isnull().sum()

Index
Year                                                            0
CoC Number                                                      0
Children of Parenting Youth                                    77
Chronically Homeless                                           33
Chronically Homeless Individuals                                0
Chronically Homeless People in Families                        33
Homeless Individuals                                            0
Homeless People in Families                                     0
Homeless Unaccompanied Children (Under 18)                     77
Homeless Unaccompanied Young Adults (Age 18-24)                77
Homeless Unaccompanied Youth (Under 25)                        77
Homeless Veterans                                              33
Parenting Youth (Under 25)                                     77
Parenting Youth Age 18-24                                      77
Parenting Youth Under 18                                       77
Sheltered Children of Parenting Youth                          77
Sheltered Chronically Homeless                                 33
Sheltered Chronically Homeless Individuals                      0
Sheltered Chronically Homeless People in Families              33
Sheltered Homeless                                              0
Sheltered Homeless Individuals                                  0
Sheltered Homeless People in Families                           0
Sheltered Homeless Unaccompanied Children (Under 18)           77
Sheltered Homeless Unaccompanied Young Adults (Age 18-24)      77
Sheltered Homeless Unaccompanied Youth (Under 25)              77
Sheltered Homeless Veterans                                    33
Sheltered Parenting Youth (Under 25)                           77
Sheltered Parenting Youth Age 18-24                            77
Sheltered Parenting Youth Under 18                             77
Total Homeless                                                  0
Unsheltered Children of Parenting Youth                        77
Unsheltered Chronically Homeless                               33
Unsheltered Chronically Homeless Individuals                    0
Unsheltered Chronically Homeless People in Families            33
Unsheltered Homeless                                            0
Unsheltered Homeless Individuals                                0
Unsheltered Homeless People in Families                         0
Unsheltered Homeless Unaccompanied Children (Under 18)         77
Unsheltered Homeless Unaccompanied Young Adults (Age 18-24)    77
Unsheltered Homeless Unaccompanied Youth (Under 25)            77
Unsheltered Homeless Veterans                                  33
Unsheltered Parenting Youth (Under 25)                         77
Unsheltered Parenting Youth Age 18-24                          77
Unsheltered Parenting Youth Under 18                           77
dtype: int64

In [20]:
df_1 = df_1.dropna(axis = 1, thresh = 77, inplace= False)

In [21]:
df_1.head()

Index,Year,CoC Number,Chronically Homeless Individuals,Homeless Individuals,Homeless People in Families,Sheltered Chronically Homeless Individuals,Sheltered Homeless,Sheltered Homeless Individuals,Sheltered Homeless People in Families,Total Homeless,Unsheltered Chronically Homeless Individuals,Unsheltered Homeless,Unsheltered Homeless Individuals,Unsheltered Homeless People in Families
0,2007,TX-500,218.0,1375.0,872.0,96.0,1798.0,945.0,853.0,2247.0,122.0,449.0,430.0,19.0
1,2007,TX-503,443.0,3116.0,2165.0,92.0,1395.0,773.0,622.0,5281.0,351.0,3886.0,2343.0,1543.0
2,2007,TX-600,574.0,2046.0,1362.0,472.0,3041.0,1683.0,1358.0,3408.0,102.0,367.0,363.0,4.0
3,2007,TX-601,479.0,1550.0,1326.0,392.0,2675.0,1349.0,1326.0,2876.0,87.0,201.0,201.0,0.0
4,2007,TX-603,208.0,804.0,437.0,72.0,968.0,531.0,437.0,1241.0,136.0,273.0,273.0,0.0

In [22]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 14 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Year                                          99 non-null     int64
 1   CoC Number                                    99 non-null     object
 2   Chronically Homeless Individuals              99 non-null     float64
 3   Homeless Individuals                          99 non-null     float64
 4   Homeless People in Families                   99 non-null     float64
 5   Sheltered Chronically Homeless Individuals    99 non-null     float64
 6   Sheltered Homeless                            99 non-null     float64
 7   Sheltered Homeless Individuals                99 non-null     float64
 8   Sheltered Homeless People in Families         99 non-null     float64
 9   Total Homeless                                99 non-null     float64
 10  Unsheltered Chronically Homeless Individuals  99 non-null     float64
 11  Unsheltered Homeless                          99 non-null     float64
 12  Unsheltered Homeless Individuals              99 non-null     float64
 13  Unsheltered Homeless People in Families       99 non-null     float64
dtypes: float64(12), int64(1), object(1)
memory usage: 11.0+ KB

In [23]:
def percentage(x):
    for columns in x.columns[3:]:
        x[columns + '(%)'] = x[columns] / x['Total Homeless']
    return x

In [24]:
percentage(df_1)

C:\Users\USER\anaconda3\envs\tensorflow_env\lib\site-packages\pandas\core\frame.py:3607: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)

Index,Year,CoC Number,Chronically Homeless Individuals,Homeless Individuals,Homeless People in Families,Sheltered Chronically Homeless Individuals,Sheltered Homeless,Sheltered Homeless Individuals,Sheltered Homeless People in Families,Total Homeless,...,Homeless People in Families(%),Sheltered Chronically Homeless Individuals(%),Sheltered Homeless(%),Sheltered Homeless Individuals(%),Sheltered Homeless People in Families(%),Total Homeless(%),Unsheltered Chronically Homeless Individuals(%),Unsheltered Homeless(%),Unsheltered Homeless Individuals(%),Unsheltered Homeless People in Families(%)
0,2007,TX-500,218.0,1375.0,872.0,96.0,1798.0,945.0,853.0,2247.0,...,0.388073,0.042724,0.800178,0.420561,0.379617,1.0,0.054295,0.199822,0.191366,0.008456
1,2007,TX-503,443.0,3116.0,2165.0,92.0,1395.0,773.0,622.0,5281.0,...,0.409960,0.017421,0.264155,0.146374,0.117781,1.0,0.066465,0.735845,0.443666,0.292180
2,2007,TX-600,574.0,2046.0,1362.0,472.0,3041.0,1683.0,1358.0,3408.0,...,0.399648,0.138498,0.892312,0.493838,0.398474,1.0,0.029930,0.107688,0.106514,0.001174
3,2007,TX-601,479.0,1550.0,1326.0,392.0,2675.0,1349.0,1326.0,2876.0,...,0.461057,0.136300,0.930111,0.469054,0.461057,1.0,0.030250,0.069889,0.069889,0.000000
4,2007,TX-603,208.0,804.0,437.0,72.0,968.0,531.0,437.0,1241.0,...,0.352135,0.058018,0.780016,0.427881,0.352135,1.0,0.109589,0.219984,0.219984,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2016,TX-607,823.0,3898.0,2150.0,316.0,3660.0,1683.0,1977.0,6048.0,...,0.355489,0.052249,0.605159,0.278274,0.326885,1.0,0.083829,0.394841,0.366237,0.028604
95,2016,TX-611,75.0,445.0,147.0,69.0,572.0,425.0,147.0,592.0,...,0.248311,0.116554,0.966216,0.717905,0.248311,1.0,0.010135,0.033784,0.033784,0.000000
96,2016,TX-624,36.0,204.0,52.0,36.0,234.0,182.0,52.0,256.0,...,0.203125,0.140625,0.914062,0.710938,0.203125,1.0,0.000000,0.085938,0.085938,0.000000
97,2016,TX-700,511.0,3055.0,976.0,127.0,2835.0,1869.0,966.0,4031.0,...,0.242124,0.031506,0.703299,0.463657,0.239643,1.0,0.095262,0.296701,0.294220,0.002481
98,2016,TX-701,10.0,80.0,81.0,6.0,150.0,74.0,76.0,161.0,...,0.503106,0.037267,0.931677,0.459627,0.472050,1.0,0.024845,0.068323,0.037267,0.031056

In [25]:
df_1

Index,Year,CoC Number,Chronically Homeless Individuals,Homeless Individuals,Homeless People in Families,Sheltered Chronically Homeless Individuals,Sheltered Homeless,Sheltered Homeless Individuals,Sheltered Homeless People in Families,Total Homeless,...,Homeless People in Families(%),Sheltered Chronically Homeless Individuals(%),Sheltered Homeless(%),Sheltered Homeless Individuals(%),Sheltered Homeless People in Families(%),Total Homeless(%),Unsheltered Chronically Homeless Individuals(%),Unsheltered Homeless(%),Unsheltered Homeless Individuals(%),Unsheltered Homeless People in Families(%)
0,2007,TX-500,218.0,1375.0,872.0,96.0,1798.0,945.0,853.0,2247.0,...,0.388073,0.042724,0.800178,0.420561,0.379617,1.0,0.054295,0.199822,0.191366,0.008456
1,2007,TX-503,443.0,3116.0,2165.0,92.0,1395.0,773.0,622.0,5281.0,...,0.409960,0.017421,0.264155,0.146374,0.117781,1.0,0.066465,0.735845,0.443666,0.292180
2,2007,TX-600,574.0,2046.0,1362.0,472.0,3041.0,1683.0,1358.0,3408.0,...,0.399648,0.138498,0.892312,0.493838,0.398474,1.0,0.029930,0.107688,0.106514,0.001174
3,2007,TX-601,479.0,1550.0,1326.0,392.0,2675.0,1349.0,1326.0,2876.0,...,0.461057,0.136300,0.930111,0.469054,0.461057,1.0,0.030250,0.069889,0.069889,0.000000
4,2007,TX-603,208.0,804.0,437.0,72.0,968.0,531.0,437.0,1241.0,...,0.352135,0.058018,0.780016,0.427881,0.352135,1.0,0.109589,0.219984,0.219984,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,2016,TX-607,823.0,3898.0,2150.0,316.0,3660.0,1683.0,1977.0,6048.0,...,0.355489,0.052249,0.605159,0.278274,0.326885,1.0,0.083829,0.394841,0.366237,0.028604
95,2016,TX-611,75.0,445.0,147.0,69.0,572.0,425.0,147.0,592.0,...,0.248311,0.116554,0.966216,0.717905,0.248311,1.0,0.010135,0.033784,0.033784,0.000000
96,2016,TX-624,36.0,204.0,52.0,36.0,234.0,182.0,52.0,256.0,...,0.203125,0.140625,0.914062,0.710938,0.203125,1.0,0.000000,0.085938,0.085938,0.000000
97,2016,TX-700,511.0,3055.0,976.0,127.0,2835.0,1869.0,966.0,4031.0,...,0.242124,0.031506,0.703299,0.463657,0.239643,1.0,0.095262,0.296701,0.294220,0.002481
98,2016,TX-701,10.0,80.0,81.0,6.0,150.0,74.0,76.0,161.0,...,0.503106,0.037267,0.931677,0.459627,0.472050,1.0,0.024845,0.068323,0.037267,0.031056

In [26]:
df_1 = df_1.drop(columns =['Chronically Homeless Individuals', 'Homeless Individuals',
       'Homeless People in Families',
       'Sheltered Chronically Homeless Individuals', 'Sheltered Homeless',
       'Sheltered Homeless Individuals',
       'Sheltered Homeless People in Families', 'Total Homeless(%)',
       'Unsheltered Chronically Homeless Individuals', 'Unsheltered Homeless',
       'Unsheltered Homeless Individuals',
       'Unsheltered Homeless People in Families'] )

In [28]:
df_1['Total Homeless'] = df_1['Total Homeless'].astype('int64')

In [29]:
df_1.head()

Index,Year,CoC Number,Total Homeless,Homeless Individuals(%),Homeless People in Families(%),Sheltered Chronically Homeless Individuals(%),Sheltered Homeless(%),Sheltered Homeless Individuals(%),Sheltered Homeless People in Families(%),Unsheltered Chronically Homeless Individuals(%),Unsheltered Homeless(%),Unsheltered Homeless Individuals(%),Unsheltered Homeless People in Families(%)
0,2007,TX-500,2247,0.611927,0.388073,0.042724,0.800178,0.420561,0.379617,0.054295,0.199822,0.191366,0.008456
1,2007,TX-503,5281,0.590040,0.409960,0.017421,0.264155,0.146374,0.117781,0.066465,0.735845,0.443666,0.292180
2,2007,TX-600,3408,0.600352,0.399648,0.138498,0.892312,0.493838,0.398474,0.029930,0.107688,0.106514,0.001174
3,2007,TX-601,2876,0.538943,0.461057,0.136300,0.930111,0.469054,0.461057,0.030250,0.069889,0.069889,0.000000
4,2007,TX-603,1241,0.647865,0.352135,0.058018,0.780016,0.427881,0.352135,0.109589,0.219984,0.219984,0.000000