In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/OmdenaAI/omdena-texas-homelessness/main/src/data/employment/Unequal%20Financial%20Impacts%20of%20the%20Pandemic%20(HPS)%20by%20Quarter.xlsx%20-%20Sheet1.csv?token=AUHOKXLMYPS3LOCRIE7ZWA3BL4WH6')
df.head()

,Unnamed: 0,Renters,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Homeowners,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,All Households,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Quarter 4 2020,NaN,"<$25,000","$25,000-$49,999","$50,000-74,999","$75,000-99,999","$100,000+",All,"<$25,000","$25,000-$49,999","$50,000-74,999","$75,000-99,999","$100,000+",All,"<$25,000","$25,000-$49,999","$50,000-74,999","$75,000-99,999","$100,000+",All
1,NaN,Behind on Housing,24.0,19.1,12.8,9.3,6.2,17.0,21.4,14.6,11.0,7.8,4.7,9.3,23.4,17.1,11.7,8.2,4.94,12.44
2,NaN,Loss of Income,55.4,56.7,52.6,47.1,40.3,52.8,44.7,40.6,38.9,38.3,32.8,37.4,51.2,47.6,42.9,40.2,33.79,43.27
3,NaN,NaN,White,Black,Hispanic,Asian,Another Race/Multiracial,All,White,Black,Hispanic,Asian,Another Race/Multiracial,All,White,Black,Hispanic,Asian,Another Race/Multiracial,All
4,NaN,Behind on Housing,11.8,27.9,20.7,17.5,20.9,17.0,6.9,17.1,15.9,12.7,12.9,9.3,8.6,23.6,18.5,14.6,17.01,12.44

This dataset has too much and is too spread apart. Rows are columns, no real direction on what is what with no source. We will not recommend the use of this dataset. It could be of some value if the data is parsed with another set that could define the data a bit more.

In [6]:
df.to_csv('unequal_financial_impacts_of_the_pandemic_by_quarter')