In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\mohit\OneDrive\Desktop\Omdena-AI\omdena-texas-homelessness\src\data\housing\2007-2020-Hosuing Inventory Count-Counts-by-State.xlsx - 2020.csv')

In [3]:
df.head()

,State,"Total Year-Round Beds (ES, TH, SH)","Total Non-DV Year-Round Beds (ES, TH, SH)","Total HMIS Year-Round Beds (ES, TH, SH)","HMIS Participation Rate for Year-Round Beds (ES, TH, SH)",Total Year-Round Beds (ES),Total Year-Round Beds (TH),Total Year-Round Beds (SH),"Total Units for Households with Children (ES, TH, SH)","Total Beds for Households with Children (ES, TH, SH)",...,Total Year-Round Beds (OPH),Total Non-DV Year-Round Beds (OPH),Total HMIS Year-Round Beds (OPH),HMIS Participation Rate for Year-Round Beds (OPH),Total Units for Households with Children (OPH),Total Beds for Households with Children (OPH),Total Beds for Households without Children (OPH),Total Beds for Households with only Children (OPH),Dedicated Veteran Beds (OPH),Dedicated Youth Beds (OPH)
0,AK,1885,1347,1122,59.52%,1410,475,0,194,722,...,92,92,92,100.00%,4,8,84,0,0,0
1,AL,2913,2291,1659,56.95%,1992,887,34,411,1134,...,40,40,32,80.00%,0,0,40,0,0,0
2,AR,1686,1193,680,40.33%,1330,356,0,181,617,...,0,0,0,.,0,0,0,0,0,0
3,AZ,6079,4943,4352,71.59%,3632,2370,77,821,2876,...,346,346,346,100.00%,75,294,52,0,33,10
4,CA,53265,48649,35666,66.96%,38241,14760,264,7344,23569,...,8707,8618,6185,71.03%,849,2684,6011,12,464,171

In [4]:
df.shape

(56, 77)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 77 columns):
 #   Column                                                     Non-Null Count  Dtype
---  ------                                                     --------------  -----
 0   State                                                      56 non-null     object
 1   Total Year-Round Beds (ES, TH, SH)                         56 non-null     int64
 2   Total Non-DV Year-Round Beds (ES, TH, SH)                  56 non-null     int64
 3   Total HMIS Year-Round Beds (ES, TH, SH)                    56 non-null     int64
 4   HMIS Participation Rate for Year-Round Beds (ES, TH, SH)   56 non-null     object
 5   Total Year-Round Beds (ES)                                 56 non-null     int64
 6   Total Year-Round Beds (TH)                                 56 non-null     int64
 7   Total Year-Round Beds (SH)                                 56 non-null     int64
 8   Total Units for Households with Children (ES, TH, SH)      56 non-null     int64
 9   Total Beds for Households with Children (ES, TH, SH)       56 non-null     int64
 10  Total Beds for Households without Children (ES, TH, SH)    56 non-null     int64
 11  Total Beds for Households with only Children (ES, TH, SH)  56 non-null     int64
 12  Dedicated Veteran Beds (ES, TH, SH)                        56 non-null     int64
 13  Dedicated Youth Beds (ES, TH, SH)                          56 non-null     int64
 14  Total Year-Round Beds (ES).1                               56 non-null     int64
 15  Total Non-DV Year-Round Beds (ES)                          56 non-null     int64
 16  Total HMIS Year-Round Beds (ES)                            56 non-null     int64
 17  HMIS Participation Rate for Year-Round Beds (ES)           56 non-null     object
 18  Total Seasonal Beds (ES)                                   56 non-null     int64
 19  Total Overflow Beds (ES)                                   56 non-null     int64
 20  Total Units for Households with Children (ES)              56 non-null     int64
 21  Total Beds for Households with Children (ES)               56 non-null     int64
 22  Total Beds for Households without Children (ES)            56 non-null     int64
 23  Total Beds for Households with only Children (ES)          56 non-null     int64
 24  Dedicated Veteran Beds (ES)                                56 non-null     int64
 25  Dedicated Youth Beds (ES)                                  56 non-null     int64
 26  Total Year-Round Beds (TH).1                               56 non-null     int64
 27  Total Non-DV Year-Round Beds (TH)                          56 non-null     int64
 28  Total HMIS Year-Round Beds (TH)                            56 non-null     int64
 29  HMIS Participation Rate for Year-Round Beds (TH)           56 non-null     object
 30  Total Units for Households with Children (TH)              56 non-null     int64
 31  Total Beds for Households with Children (TH)               56 non-null     int64
 32  Total Beds for Households without Children (TH)            56 non-null     int64
 33  Total Beds for Households with only Children (TH)          56 non-null     int64
 34  Dedicated Veteran Beds (TH)                                56 non-null     int64
 35  Dedicated Youth Beds (TH)                                  56 non-null     int64
 36  Total Year-Round Beds (SH).1                               56 non-null     int64
 37  Total Non-DV Year-Round Beds (SH)                          56 non-null     int64
 38  Total HMIS Year-Round Beds (SH)                            56 non-null     int64
 39  HMIS Participation Rate for Year-Round Beds (SH)           56 non-null     object
 40  Total Units for Households with Children (SH)              56 non-null     int64
 41  Total Beds for Households with Children (SH)               56 non-null     int64
 42  Total Beds for Households without Children (SH)            56 non-null     int64
 43  Total Beds for Households with only Children (SH)          56 non-null     int64
 44  Dedicated Veteran Beds (SH)                                56 non-null     int64
 45  Dedicated Youth Beds (SH)                                  56 non-null     int64
 46  Total Year-Round Beds (RRH)                                56 non-null     int64
 47  Total Non-DV Year-Round Beds (RRH)                         56 non-null     int64
 48  Total HMIS Year-Round Beds (RRH)                           56 non-null     int64
 49  HMIS Participation Rate for Year-Round Beds (RRH)          56 non-null     object
 50  Total Units for Households with Children (RRH)             56 non-null     int64
 51  Total Beds for Households with Children (RRH)              56 non-null     int64
 52  Total Beds for Households without Children (RRH)           56 non-null     int64
 53  Total Beds for Households with only Children (RRH)         56 non-null     int64
 54  Dedicated Veteran Beds (RRH)                               56 non-null     int64
 55  Dedicated Youth Beds (RRH)                                 56 non-null     int64
 56  Total Year-Round Beds (PSH)                                56 non-null     int64
 57  Total Non-DV Year-Round Beds (PSH)                         56 non-null     int64
 58  Total HMIS Year-Round Beds (PSH)                           56 non-null     int64
 59  HMIS Participation Rate for Year-Round Beds (PSH)          56 non-null     object
 60  Total Units for Households with Children (PSH)             56 non-null     int64
 61  Total Beds for Households with Children (PSH)              56 non-null     int64
 62  Total Beds for Households without Children (PSH)           56 non-null     int64
 63  Total Beds for Households with only Children (PSH)         56 non-null     int64
 64  Dedicated Veteran Beds (PSH)                               56 non-null     int64
 65  Dedicated Youth Beds (PSH)                                 56 non-null     int64
 66  Dedicated Chronically Homeless Beds (PSH)                  56 non-null     int64
 67  Total Year-Round Beds (OPH)                                56 non-null     int64
 68  Total Non-DV Year-Round Beds (OPH)                         56 non-null     int64
 69  Total HMIS Year-Round Beds (OPH)                           56 non-null     int64
 70  HMIS Participation Rate for Year-Round Beds (OPH)          56 non-null     object
 71  Total Units for Households with Children (OPH)             56 non-null     int64
 72  Total Beds for Households with Children (OPH)              56 non-null     int64
 73  Total Beds for Households without Children (OPH)           56 non-null     int64
 74  Total Beds for Households with only Children (OPH)         56 non-null     int64
 75  Dedicated Veteran Beds (OPH)                               56 non-null     int64
 76  Dedicated Youth Beds (OPH)                                 56 non-null     int64
dtypes: int64(69), object(8)
memory usage: 33.8+ KB

In [6]:
df.isnull().sum()

State                                                       0
Total Year-Round Beds (ES, TH, SH)                          0
Total Non-DV Year-Round Beds (ES, TH, SH)                   0
Total HMIS Year-Round Beds (ES, TH, SH)                     0
HMIS Participation Rate for Year-Round Beds (ES, TH, SH)    0
                                                           ..
Total Beds for Households with Children (OPH)               0
Total Beds for Households without Children (OPH)            0
Total Beds for Households with only Children (OPH)          0
Dedicated Veteran Beds (OPH)                                0
Dedicated Youth Beds (OPH)                                  0
Length: 77, dtype: int64

In [7]:
df.nunique()

State                                                       56
Total Year-Round Beds (ES, TH, SH)                          56
Total Non-DV Year-Round Beds (ES, TH, SH)                   55
Total HMIS Year-Round Beds (ES, TH, SH)                     56
HMIS Participation Rate for Year-Round Beds (ES, TH, SH)    55
                                                            ..
Total Beds for Households with Children (OPH)               37
Total Beds for Households without Children (OPH)            43
Total Beds for Households with only Children (OPH)           6
Dedicated Veteran Beds (OPH)                                25
Dedicated Youth Beds (OPH)                                  14
Length: 77, dtype: int64

In [8]:
# For NULL values we will keep those columns which has around 50% of NAN data

n =int( 0.5 * df.shape[0])

# For Unique values we will keep only those columns which has around 25% of unique values
p = int(0.1 * df.shape[0])

col = df.columns
for i in range(len(col)):
    if df[col[i]].isnull().sum() > n:
        df.drop([col[i]] , axis= 1 , inplace= True)

# After dropping some columns we will make around list of columns
col = df.select_dtypes('object').columns

for i in range(len(col)):
    if df[col[i]].nunique() > p:
        df.drop([col[i]] , axis=1 , inplace=True)

In [9]:
df.shape

(56, 69)

In [10]:
df.nunique()

Total Year-Round Beds (ES, TH, SH)                    56
Total Non-DV Year-Round Beds (ES, TH, SH)             55
Total HMIS Year-Round Beds (ES, TH, SH)               56
Total Year-Round Beds (ES)                            56
Total Year-Round Beds (TH)                            56
                                                      ..
Total Beds for Households with Children (OPH)         37
Total Beds for Households without Children (OPH)      43
Total Beds for Households with only Children (OPH)     6
Dedicated Veteran Beds (OPH)                          25
Dedicated Youth Beds (OPH)                            14
Length: 69, dtype: int64

In [11]:
df.head()

,"Total Year-Round Beds (ES, TH, SH)","Total Non-DV Year-Round Beds (ES, TH, SH)","Total HMIS Year-Round Beds (ES, TH, SH)",Total Year-Round Beds (ES),Total Year-Round Beds (TH),Total Year-Round Beds (SH),"Total Units for Households with Children (ES, TH, SH)","Total Beds for Households with Children (ES, TH, SH)","Total Beds for Households without Children (ES, TH, SH)","Total Beds for Households with only Children (ES, TH, SH)",...,Dedicated Chronically Homeless Beds (PSH),Total Year-Round Beds (OPH),Total Non-DV Year-Round Beds (OPH),Total HMIS Year-Round Beds (OPH),Total Units for Households with Children (OPH),Total Beds for Households with Children (OPH),Total Beds for Households without Children (OPH),Total Beds for Households with only Children (OPH),Dedicated Veteran Beds (OPH),Dedicated Youth Beds (OPH)
0,1885,1347,1122,1410,475,0,194,722,1141,22,...,459,92,92,92,4,8,84,0,0,0
1,2913,2291,1659,1992,887,34,411,1134,1736,43,...,943,40,40,32,0,0,40,0,0,0
2,1686,1193,680,1330,356,0,181,617,1069,0,...,22,0,0,0,0,0,0,0,0,0
3,6079,4943,4352,3632,2370,77,821,2876,3170,33,...,1903,346,346,346,75,294,52,0,33,10
4,53265,48649,35666,38241,14760,264,7344,23569,29515,181,...,23391,8707,8618,6185,849,2684,6011,12,464,171

In [12]:
df.to_csv(r"C:\Users\mohit\OneDrive\Desktop\Omdena-AI\omdena-texas-homelessness\src\cleaned data\2007-2020-Housing-Inventory-COC.csv")